### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lEuYKT/txtv/

### ISSUE THREAD

**Issue by elmaxe** [voidcase/txtv#2]
```
$ pip install --user txtv
Collecting txtv
  Downloading https://files.pythonhosted.org/packages/01/ed/18ea7b3153a23d571cb880c83d90f9976ca0111e136e4dc01c29749bddea/txtv-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lEuYKT/txtv/setup.py", line 17
        download_url=f'https://github.com/voidcase/txtv/archive/v{VERSION}.tar.gz',
                                                                                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lEuYKT/txtv/
```

**Comment by voidcase** [comment]
Looks like you are using pre-3.6 python. Try `pip3 install --user txtv`.

**Comment by elmaxe** [comment]
Python 3.6.8

**Comment by voidcase** [comment]
@elmaxe Did it work?
