### ISSUE TITLE
README.MD needs a little update

### ISSUE THREAD

**Issue by beltet** [voidcase/txtv#3]
I had to install it through Python3(pip3) otherwise I got various errors.

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting txtv
  Using cached txtv-1.2.1.tar.gz (7.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-RN6fhz/txtv/setup.py'"'"'; __file__='"'"'/tmp/pip-install-RN6fhz/txtv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-RN6fhz/txtv/pip-egg-info
         cwd: /tmp/pip-install-RN6fhz/txtv/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-RN6fhz/txtv/setup.py", line 17
        download_url=f'https://github.com/voidcase/txtv/archive/v{VERSION}.tar.gz',
                                                                                 ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

Running POP_OS! 19.10

**Comment by voidcase** [comment]
Thanks :)
[I have updated the readme and the setup.py now](https://github.com/voidcase/txtv/commit/72741790db75881ac35042d73179980cfa9df0d4)
